#!/usr/bin/env python3
"""
PulseGuard - Retrain the model using ALL live data currently in Firebase.

What this does:
  1. Downloads every reading from Firebase /readings_only (sensor INPUT only)
  2. Runs the full training pipeline (EDA -> labels -> model comparison -> model.pkl)
  3. Copies the trained model into flask_api/ so the API picks it up
  4. Prints an honest report of what the new model learned

IMPORTANT - what this does NOT do:
  - It does NOT use /prediction as training data (predictions are OUTPUT only)
  - The labels are still RULE-GENERATED thresholds, not human-verified failure
    labels, so the reported accuracy means "learned the rules well", not
    "predicts real failures with X% accuracy".

Usage:
    cd ml
    python retrain_from_firebase.py
    (then restart the Flask API so it loads the new model.pkl)
"""

import sys
import shutil
from pathlib import Path

# Allow importing the training pipeline from this folder
sys.path.insert(0, str(Path(__file__).parent))

from train_model import run_training_pipeline, MODEL_PATH  # noqa: E402

FLASK_MODEL_PATH = Path(__file__).parent.parent / "flask_api" / "model.pkl"

FIREBASE_URL = "https://pulseguard-7ae33-default-rtdb.firebaseio.com/"


def main():
    print("=" * 60)
    print("PULSEGUARD - RETRAIN WITH LIVE FIREBASE DATA")
    print("=" * 60)
    print()
    print("Source : Firebase /readings_only (raw sensor INPUT only)")
    print("Labels : rule-based thresholds (NOT human-verified)")
    print("Output : ml/model.pkl -> copied to flask_api/model.pkl")
    print()

    # 1. Train on all live data currently in Firebase
    result = run_training_pipeline(use_firebase=True, firebase_url=FIREBASE_URL)

    if result is None:
        print("\n[ABORT] Training failed or no data available.")
        print("The existing model in flask_api/model.pkl is untouched.")
        return 1

    # 2. Deploy the new model to the Flask API
    shutil.copy(MODEL_PATH, FLASK_MODEL_PATH)
    print()
    print(f"[OK] New model deployed to: {FLASK_MODEL_PATH}")

    # 3. Honest report
    print()
    print("=" * 60)
    print("RETRAIN COMPLETE - WHAT THIS ACTUALLY MEANS")
    print("=" * 60)
    print("""
The new model was trained on ALL live readings currently in Firebase
(including the motor-heating session you just recorded).

BUT - be accurate about this:
  * Labels were still generated by rules (temp/vibration thresholds).
  * Accuracy reported by training = how well the model reproduces
    those rules, NOT real-world failure-prediction accuracy.
  * What DID improve: the model now reflects YOUR machine's real
    temperature/vibration range instead of mostly old test data.

Next step for genuine accuracy: while watching the machine, tag a few
sessions yourself as normal / warning / critical, store them with a
'label' field, and extend train_model.py to prefer human labels when
present. Then retraining validates against reality instead of rules.
""")
    print("NOW RESTART the Flask API so it loads the new model:")
    print("  - Close the 'PulseGuard API' window")
    print("  - cd flask_api && python app.py")
    return 0


if __name__ == "__main__":
    sys.exit(main())
